### ISSUE TITLE
Add mediumkreation's Indian list

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#608] opened 2022-04-24 13:08 UTC
`https://github.com/mediumkreation/IndianList`
The list has been well-maintained for long time now.

**Comment by DandelionSprout** [comment] 2022-04-25 02:55
Probably a duplicate of #550, but I approve of this re-posting if it speeds up the addition process.

**Comment by zloyden** [comment] 2022-04-25 08:14
According to our rules, this repo doesn't have enough stars. Nevertheless, I suppose we can add it.

**Comment by DandelionSprout** [comment] 2022-04-25 08:47
A fair few of the repo's rules have struck me as odd for some time now, especially the "10 updates per month" rule. So I guess many of the rules can be bypassed, especially for regional lists.

**Comment by Yuki2718** [comment] 2022-04-25 10:25
> Probably a duplicate of 

Oh, sorry I forgot to check.

**Closed** 2022-05-05 07:07 UTC
