### ISSUE TITLE
Add Dandelion Sprout's Annoyances List

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#400] opened 2020-11-25 12:05 UTC
Here it is:
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList

Category: annoyances
Tags: annoyances
Description: see https://github.com/AdguardTeam/FiltersRegistry/issues/400#issuecomment-792999470

**Comment by DandelionSprout** [comment] 2020-11-25 12:10
The description would (as far as I can determine in a hurry) be *"This list is made in the style of AdGuard's and Fanboy's annoyances lists. It combines many of Dandelion Sprout's proudest and most frequently maintained international lists, as a curated list for simplicity's sake."*

I tend to add emojis to all of my list titles to make them easier to identify, but other than that they serve no real purpose and can be removed in their listings on this repo.

**Comment by DandelionSprout** [comment] 2021-03-07 19:25
Are there any requirements or roadpaths remaining by now, before this and/or https://github.com/AdguardTeam/FiltersRegistry/issues/401 could become evaluated for inclusion?

If active maintenance is a requirement, I can prove that with at least relative ease.

**Comment by ameshkov** [comment] 2021-03-08 18:57
Tbh, both looks good, thank you!

Could you please specify the following props so that we could add them:

* Title
* Description
* Homepage

**Comment by DandelionSprout** [comment] 2021-03-08 19:07
* Title: Dandelion Sprout's Annoyances List
* Description: "This list is made in the style of AdGuard's and Fanboy's annoyances lists. It combines many of Dandelion Sprout's proudest and most frequently maintained international lists, as a curated compilation for simplicity's sake."
* Homepage: https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#-english

**Comment by Alex-302** [comment] 2021-03-08 20:19
@DandelionSprout is it by design - `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList` without extension?

**Comment by Alex-302** [comment] 2021-03-08 20:28
@ameshkov It seems filters compiler cannot download it. But includes with extension downloaded successfully.

**Comment by DandelionSprout** [comment] 2021-03-08 20:36
I can give it an extension, but it'll take me 2 days to do so properly (e.g. by also changing existing links on FilterLists.com, among other places).

**Comment by Alex-302** [comment] 2021-03-08 20:37
Maybe it can be fixed in FiltersCompiler.

**Comment by ameshkov** [comment] 2021-03-08 22:09
@DandelionSprout please don't bother, this needs to be fixed on our side.

**Comment by DandelionSprout** [comment] 2021-04-04 02:32
Is everything going well with that on you guys' end?

**Comment by ameshkov** [comment] 2021-04-04 18:55
@DandelionSprout sorry for the delay, we're waiting for @tvinzz to fix https://github.com/AdguardTeam/FiltersCompiler/issues/101#issuecomment-808364156

And he's quite busy with AG for Safari release so the PR is stalling.

**Comment by ameshkov** [comment] 2021-05-07 05:34
> If it's important to also prevent the Yandex-Samsung Content Blocker from loading that file as well, give me a headsup about it.

Yeah, it's also pretty limited in what it can do.

We're almost finished with Safari update so we'll get back to this PRs soon.

**Comment by DandelionSprout** [comment] 2021-06-15 10:56
How about now, seeing as we're in mid-June and 7 months have passed?

**Comment by ameshkov** [comment] 2021-06-21 06:26
@DandelionSprout yup, thanks for pinging us. We have quite a lot of lists to review and we've decided to first come up with criteria for inclusion and a general clean-up of the FiltersRegistry. It should be finished by the end of this week.

**Comment by DandelionSprout** [comment] 2021-07-09 08:16
From what I can tell, this list meets all 11 criterias that are at https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository at the time of writing.

Of *Annoyances List*'s 20 component lists, I can testify first-hand to 18 of them having no problematic entries. The remaining two, `LegitimateURLShortener.txt` and `Anti-'Custom%20cursors'%20List.txt`, require additional feedback from end-users before reaching perfection (with the easiest way to get feedback being to get my list(s) included in AdGuard), as there's no other way at all to figure out which entries that could turn out to be problematic or not.

**Closed** 2021-07-13 17:57 UTC
Labels: enhancement
