### ISSUE TITLE
Chinese AD blacklist for mobile apps

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/FiltersRegistry#475] opened 2021-05-13 11:39 UTC
https://github.com/banbendalao/ADgk/blob/master/ADgk.txt

**Comment by Alex-302** [comment] 2021-05-24 10:12
Duplicate of https://github.com/AdguardTeam/FiltersRegistry/pull/343

**Closed by Alex-302** 2021-05-24 10:12 UTC
